version: '3.7'

services:
  todo_be:
    environment:
      ENVIRONMENT: local
      FACEBOOK_ID: ${FACEBOOK_ID}
      PORT: ${PORT}
    container_name: todo_be
    # network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app 
      
#        frontend:
#     depends_on:
#       - todo_be
# # volumes:
#   app:
#     source:
#     external: true
# ----------------------------test


